schema_version = 1

id = "onedark-pro-blur-theme"
name = "OneDark Pro Blur"
version = "1.0.0"

authors = ["MadKarma"]
description = "OneDark Pro port for Zed with blur effects"
repository = "https://github.com/madkarmaa/zed-onedark-pro-blur"
